/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaNativeDemo */

#ifndef _Included_JavaNativeDemo
#define _Included_JavaNativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaNativeDemo
 * Method:    printFromNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaNativeDemo_printFromNative
  (JNIEnv *env, jobject thisObj) {
    printf("Hello from C Native Code!\n");
  }

#ifdef __cplusplus
}
#endif
#endif
