create table players(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(100) not null,
	dob date not null,
	wage numeric(11,2) not null,
	height decfloat not null,
	shirt int not null
);