CREATE TABLE departments (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE employees (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	department_id BIGINT,
	FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE
);